//
//  NotificationNameDefinition.h
//  Acquirer
//
//  Created by chinaPnr on 13-7-11.
//  Copyright (c) 2013年 chinaPnr. All rights reserved.
//

#ifndef NotificationNameDefinition_h
#define NotificationNameDefinition_h


#define NOTIFICATION_MESSAGE @"NOTIFICATION_MESSAGE"
#define NOTIFICATION_TYPE @"NOTIFICATION_TYPE"

#define NOTIFICATION_TITANIUM_PROMPT @"NOTIFICATION_TITANIUM_PROMPT"
//Acquirer local error
#define NOTIFICATION_TYPE_ERROR @"NOTIFICATION_TYPE_ERROR"
//Acquirer server error
#define NOTIFICATION_TYPE_WARNING @"NOTIFICATION_TYPE_WARNING"
//Acquirer success
#define NOTIFICATION_TYPE_SUCCESS @"NOTIFICATION_TYPE_SUCCESS"

#define NOTIFICATION_UI_AUTO_PROMPT @"NOTIFICATION_UI_AUTO_PROMPT"
#define NOTIFICATION_HIDE_UI_PROMPT @"NOTIFICATION_HIDE_UI_PROMPT"

#define NOTIFICATION_SYS_AUTO_PROMPT @"NOTIFICATION_SYS_AUTO_PROMPT"

#define NOTIFICATION_REQUIRE_USER_LOGIN @"NOTIFICATION_REQUIRE_USER_LOGIN"

#define NOTIFICATION_REFRESH_ACCOUNT @"NOTIFICATION_REFRESH_ACCOUNT"


#endif
